version: '3.8'

services:
  api:
    container_name: 'invoicer_api'
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3001:3001
    depends_on:
      - postgres_db
    networks:
      invoicer_network:

  postgres_db:
    image: postgres
    container_name: 'invoicer_db'
    restart: unless-stopped
    environment:
      POSTGRES_USER: invoicer_user_PDHWUQBFIMTASDB
      POSTGRES_PASSWORD: ABkMQpZ4jQhGnsq
      POSTGRES_DATABASE: invoicer_db_PDHWUQBFIMTASDB
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      invoicer_network:

volumes:
  postgres_data:

networks:
  invoicer_network:
    driver: bridge
